macro(h1)
  string(REGEX REPLACE "." "=" _msg_h1 "${ARGV}")
  message("")
  message("${_msg_h1}")
  message("${ARGV}")
  message("${_msg_h1}")
  message("")
endmacro()

macro(h2)
  string(REGEX REPLACE "." "-" _msg_h2 "${ARGV}")
  message("")
  message("${_msg_h2}")
  message("${ARGV}")
  message("${_msg_h2}")
  message("")
endmacro()

macro(h3)
  string(REGEX REPLACE "." "=" _msg_h3 "${ARGV}")
  message("")
  message("${ARGV}")
  message("${_msg_h3}")
  message("")
endmacro()

macro(h4)
  string(REGEX REPLACE "." "-" _msg_h4 "${ARGV}")
  message("")
  message("${ARGV}")
  message("${_msg_h4}")
  message("")
endmacro()
